# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  sonar_org: jlriom-az
  sonar_proj: Play
  sonar_host: https://sonarcloud.io

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup Sonar
      run: dotnet tool install --global dotnet-sonarscanner
        
    - name: Start Sonnar scanner
      run: dotnet sonarscanner begin /o:${{env.sonar_org}} /k:${{env.sonar_proj}} /d:sonar.host.url=${{env.sonar_host}} /d:sonar.token=${{ secrets.SONAR_TOKEN }}
      
    - name: Build
      run: dotnet build 

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Finish Sonnar scanner
      run: dotnet sonarscanner end /d:sonar.token=${{ secrets.SONAR_TOKEN }} 

        
